/**
 * Background Shader Presets
 * Phase 3: Parameter combinations for different visual styles
 */

export const backgroundPresets = {
  // Default fog appearance
  default: {
    name: "Default Fog",
    description: "Soft, billowing fog with gentle movement",
    parameters: {
      u_zoom: 0.1,
      u_noiseScale: 1.6,
      u_octaves: 1,
      u_lacunarity: 1.8,
      u_gain: 0.5,
      u_turbulence: 0.2,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.0,
      u_detailScale: 1.0,
      u_detailAmount: 0.0,
      u_speed: 0.04,
      u_directionX: 0.5,
      u_directionY: 0.3,
      u_modulationSpeed: 0.28,
      u_modulationIntensity: 12.0,
      u_turbulenceModulation: 2.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.01,
      u_noiseScaleModulation: 0.0,
      u_gainModulation: 0.0,
      u_colorSpreadModulation: 0.0,
      u_colorShiftModulation: 0.0,
      u_softness: 0.2,
      u_contrast: 0.75,
      u_brightness: 1.25,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.5,
      u_colorMix2: 0.5,
      u_colorSpread: 0.66,
      u_colorSeparation: 0.3,
      u_colorBands: 0.0,
      u_grainIntensity: 0.2,
      u_grainSpeed: 20.0,
      u_grainSize: 2100.0,
      u_grainBlendMode: 2,
      u_grainAspect: 1.0,
      u_grainComplexity: 1.0,
      u_circularMotionIntensity: 0.3,
      u_evolutionSpeed: 0.15,
      u_layerBlend: 0.3,
      u_colorEvolutionSpeed: 0.1,
      u_rippleFrequency: 23.8,
      u_rippleStrength: 0.128,
      u_quantizeStep: 0.0,
      u_mirrorX: 0.0,
      u_mirrorY: 0.0,

      // Dynamic Pattern Morphing (off by default for stability)
      u_patternMorph: 0.0,
      u_lacunarityOscillation: 0.5,
      u_gainOscillation: 0.3,
      u_warpFeedback: 0.2,
      u_spectralBreathing: 0.4,

      // Base Pattern Complexity (off by default for backward compatibility)
      u_warpLayers: 0.0,
      u_noiseDistortion: 0.0,
      u_turbulentFbm: 0.0,
      u_layerInteraction: 0.0,

      // Animation Balance
      u_translationScale: 1.0,

      // Phase 6: Liquid-Chromatic
      u_iridescenceStrength: 0.14,
      u_fresnelStrength: 250.0,
      u_specularStrength: 7.5,
      u_flakeStrength: 0.0,
      u_flakeScale: 1500.0,

      // Phase 1: Spectral Separation overrides (for default preset usage)
      u_baseWeight: 0.3,
      u_midWeight: 1.0,
      u_highWeight: 0.68,
      
      // Composition
      u_vignetteStrength: 0.12,
      u_vignetteRadius: 0.12,
    },
  },

  // Smooth, dreamy fog
  dreamyFog: {
    name: "Dreamy Fog",
    description: "Very soft, ethereal fog with minimal detail",
    parameters: {
      u_zoom: 0.4,
      u_noiseScale: 1.5,
      u_octaves: 3,
      u_lacunarity: 2.0,
      u_gain: 0.6,
      u_turbulence: 0.3,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.0,
      u_detailScale: 6.0,
      u_detailAmount: 0.1,
      u_speed: 0.15,
      u_directionX: 0.3,
      u_directionY: 0.4,
      u_modulationSpeed: 0.0,
      u_modulationIntensity: 1.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.0,
      u_softness: 0.7,
      u_contrast: 0.8,
      u_brightness: 1.1,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.6,
      u_colorMix2: 0.6,
      u_colorSpread: 0.7,
      u_colorSeparation: 0.6,
      u_colorBands: 0.0,
      u_grainIntensity: 0.05,
      u_grainSpeed: 0.8,
      u_grainSize: 120.0,
      u_grainBlendMode: 0,
      u_grainAspect: 0.0,
      u_grainComplexity: 0.6,
      u_circularMotionIntensity: 0.2,
      u_evolutionSpeed: 0.1,
      u_layerBlend: 0.2,
      u_colorEvolutionSpeed: 0.05,
    },
  },

  // Dense, heavy fog
  denseFog: {
    name: "Dense Fog",
    description: "Thick, heavy fog with more defined shapes",
    parameters: {
      u_zoom: 0.6,
      u_noiseScale: 2.5,
      u_octaves: 3,
      u_lacunarity: 2.1,
      u_gain: 0.4,
      u_turbulence: 0.6,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.15,
      u_detailScale: 10.0,
      u_detailAmount: 0.2,
      u_speed: 0.18,
      u_directionX: 0.4,
      u_directionY: 0.2,
      u_modulationSpeed: 0.0,
      u_modulationIntensity: 1.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.0,
      u_softness: 0.35,
      u_contrast: 1.2,
      u_brightness: 0.95,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.4,
      u_colorMix2: 0.4,
      u_colorSpread: 0.3,
      u_colorSeparation: 0.8,
      u_colorBands: 0.0,
      u_grainIntensity: 0.12,
      u_grainSpeed: 1.2,
      u_grainSize: 180.0,
      u_grainBlendMode: 1,
      u_grainAspect: 0.0,
      u_grainComplexity: 0.6,
    },
  },

  // Wispy, fast-moving clouds
  wispyClouds: {
    name: "Wispy Clouds",
    description: "Fast, streaky clouds with sharp edges",
    parameters: {
      u_zoom: 0.7,
      u_noiseScale: 3.0,
      u_octaves: 3,
      u_lacunarity: 2.3,
      u_gain: 0.45,
      u_turbulence: 0.4,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.4,
      u_detailScale: 12.0,
      u_detailAmount: 0.25,
      u_speed: 0.5,
      u_directionX: 0.8,
      u_directionY: 0.2,
      u_modulationSpeed: 0.0,
      u_modulationIntensity: 1.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.0,
      u_softness: 0.25,
      u_contrast: 1.3,
      u_brightness: 1.0,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.5,
      u_colorMix2: 0.5,
      u_colorSpread: 0.4,
      u_colorSeparation: 0.65,
      u_colorBands: 0.0,
      u_grainIntensity: 0.15,
      u_grainSpeed: 2.0,
      u_grainSize: 200.0,
      u_grainBlendMode: 0,
      u_grainAspect: 0.0,
      u_grainComplexity: 0.6,
    },
  },

  // Liquid-like, flowing appearance
  liquidFlow: {
    name: "Liquid Flow",
    description: "Liquid-like appearance with strong distortion",
    parameters: {
      u_zoom: 0.8,
      u_noiseScale: 2.2,
      u_octaves: 3,
      u_lacunarity: 2.2,
      u_gain: 0.5,
      u_turbulence: 1.2,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.0,
      u_detailScale: 9.0,
      u_detailAmount: 0.2,
      u_speed: 0.35,
      u_directionX: 0.6,
      u_directionY: 0.5,
      u_modulationSpeed: 0.0,
      u_modulationIntensity: 1.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.0,
      u_softness: 0.4,
      u_contrast: 1.1,
      u_brightness: 1.0,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.5,
      u_colorMix2: 0.5,
      u_colorSpread: 0.6,
      u_colorSeparation: 0.5,
      u_colorBands: 0.0,
      u_grainIntensity: 0.06,
      u_grainSpeed: 0.8,
      u_grainSize: 140.0,
      u_grainBlendMode: 0,
      u_grainAspect: 0.0,
      u_grainComplexity: 0.6,
    },
  },

  // Turbulent, chaotic energy
  turbulent: {
    name: "Turbulent Energy",
    description: "Chaotic, energetic flow with high distortion",
    parameters: {
      u_zoom: 1.0,
      u_noiseScale: 2.8,
      u_octaves: 3,
      u_lacunarity: 2.4,
      u_gain: 0.45,
      u_turbulence: 1.5,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.2,
      u_detailScale: 15.0,
      u_detailAmount: 0.3,
      u_speed: 0.6,
      u_directionX: 0.7,
      u_directionY: 0.6,
      u_modulationSpeed: 0.0,
      u_modulationIntensity: 1.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.0,
      u_softness: 0.3,
      u_contrast: 1.4,
      u_brightness: 0.98,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.4,
      u_colorMix2: 0.6,
      u_colorSpread: 0.5,
      u_colorSeparation: 0.75,
      u_colorBands: 0.0,
      u_grainIntensity: 0.18,
      u_grainSpeed: 3.0,
      u_grainSize: 220.0,
      u_grainBlendMode: 2,
      u_grainAspect: 0.0,
      u_grainComplexity: 0.6,
      u_circularMotionIntensity: 0.7,
      u_evolutionSpeed: 0.4,
      u_layerBlend: 0.7,
      u_colorEvolutionSpeed: 0.3,
    },
  },

  // Calm, smooth waves
  calmWaves: {
    name: "Calm Waves",
    description: "Gentle, wave-like undulations",
    parameters: {
      u_zoom: 0.3,
      u_noiseScale: 1.8,
      u_octaves: 3,
      u_lacunarity: 2.0,
      u_gain: 0.55,
      u_turbulence: 0.7,
      u_warpOctaves: 3,
      u_ridgeAmount: 0.0,
      u_detailScale: 7.0,
      u_detailAmount: 0.12,
      u_speed: 0.2,
      u_directionX: 0.2,
      u_directionY: 0.5,
      u_modulationSpeed: 0.0,
      u_modulationIntensity: 1.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.0,
      u_softness: 0.6,
      u_contrast: 0.9,
      u_brightness: 1.05,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.6,
      u_colorMix2: 0.5,
      u_colorSpread: 0.65,
      u_colorSeparation: 0.5,
      u_colorBands: 0.0,
      u_grainIntensity: 0.04,
      u_grainSpeed: 0.6,
      u_grainSize: 100.0,
      u_grainBlendMode: 3,
      u_grainAspect: 0.0,
      u_grainComplexity: 0.6,
      u_circularMotionIntensity: 0.2,
      u_evolutionSpeed: 0.1,
      u_layerBlend: 0.2,
      u_colorEvolutionSpeed: 0.05,
    },
  },

  // Sharp, defined ridges
  mountainRidges: {
    name: "Mountain Ridges",
    description: "Sharp, ridge-like features",
    parameters: {
      u_zoom: 0.6,
      u_noiseScale: 2.5,
      u_octaves: 3,
      u_lacunarity: 2.2,
      u_gain: 0.4,
      u_turbulence: 0.5,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.8,
      u_detailScale: 10.0,
      u_detailAmount: 0.18,
      u_speed: 0.15,
      u_directionX: 0.3,
      u_directionY: 0.2,
      u_modulationSpeed: 0.0,
      u_modulationIntensity: 1.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.0,
      u_softness: 0.2,
      u_contrast: 1.5,
      u_brightness: 0.95,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.45,
      u_colorMix2: 0.45,
      u_colorSpread: 0.35,
      u_colorSeparation: 0.8,
      u_colorBands: 0.0,
      u_grainIntensity: 0.1,
      u_grainSpeed: 1.0,
      u_grainSize: 160.0,
      u_grainBlendMode: 1,
      u_grainAspect: 0.0,
      u_grainComplexity: 0.6,
      u_circularMotionIntensity: 0.3,
      u_evolutionSpeed: 0.12,
      u_layerBlend: 0.25,
      u_colorEvolutionSpeed: 0.08,
    },
  },

  // About page custom tuning
  about: {
    name: "About Page",
    description: "Custom About Me background",
    parameters: {
      u_zoom: 0.1,
      u_noiseScale: 1.6,
      u_octaves: 2,
      u_lacunarity: 2.5,
      u_gain: 0.35,
      u_turbulence: 2.0,
      u_warpOctaves: 2,
      u_ridgeAmount: 0.0,
      u_detailScale: 1.0,
      u_detailAmount: 0.0,
      u_speed: 0.04,
      u_directionX: 0.5,
      u_directionY: 0.3,
      u_modulationSpeed: 0.4,
      u_modulationIntensity: 12.0,
      u_turbulenceModulation: 0.0,
      u_zoomModulation: 0.0,
      u_colorModulation: 0.0,
      u_rotationModulation: 0.01,
      u_noiseScaleModulation: 0.0,
      u_gainModulation: 0.0,
      u_colorSpreadModulation: 0.0,
      u_colorShiftModulation: 0.0,
      u_softness: 0.0,
      u_contrast: 0.5,
      u_brightness: 1.5,
      u_exposure: 1.0,
      u_blackLevel: 0.0,
      u_colorMix1: 0.64,
      u_colorMix2: 0.5,
      u_colorSpread: 0.6,
      u_colorSeparation: 0.4,
      u_colorBands: 0.0,
      u_grainIntensity: 0.56,
      u_grainSpeed: 30.0,
      u_grainSize: 2100.0,
      u_grainBlendMode: 2,
      u_grainAspect: 1.0,
      u_grainComplexity: 1.0,
      u_circularMotionIntensity: 0.3,
      u_evolutionSpeed: 0.15,
      u_layerBlend: 0.3,
      u_colorEvolutionSpeed: 0.1,
      
      // Phase 1: Spectral Separation
      u_baseWeight: 1.2,
      u_midWeight: 0.7,
      u_highWeight: 0.25,
      
      // Phase 2: Advanced Distortion & Flow
      u_warpScale: 1.0,
      u_flowType: 0.0,
      
      // Phase 3: Texture & Structure (Worley)
      u_noiseType: 0.0,
      u_cellScale: 2.0,
      u_cellJitter: 1.0,

      // Phase 4: Composition & Masking
      u_vignetteStrength: 0.12,
      u_vignetteRadius: 0.12,
      u_centerMaskStrength: 0.0,
      u_centerMaskSize: 0.3,
      u_detailMasking: 0.0,

      // Phase 5: Post-Processing & Stylization
      u_edgeEnhance: 0.0,
      u_postPosterize: 0.0,

      // Phase 6: Liquid-Chromatic Post-Processing
      u_iridescenceStrength: 0.14,
      u_fresnelStrength: 250.0,
      u_specularStrength: 0.44,
      u_flakeStrength: 0.0,
      u_flakeScale: 1500.0,

      u_rippleFrequency: 23.8,
      u_rippleStrength: 0.1,
      u_quantizeStep: 0.0,
      u_mirrorX: 0.0,
      u_mirrorY: 0.0,

      // Pattern Morphing
      u_patternMorph: 0.0,
      u_lacunarityOscillation: 0.5,
      u_gainOscillation: 0.3,
      u_warpFeedback: 0.2,
      u_spectralBreathing: 0.4,

      // Base Pattern Complexity
      u_warpLayers: 0.0,
      u_noiseDistortion: 0.0,
      u_turbulentFbm: 0.0,
      u_layerInteraction: 0.0,
    },
  },
};

/**
 * Get a preset by name
 * @param {string} presetName - Name of the preset
 * @returns {Object|null} Preset parameters or null if not found
 */
export function getPreset(presetName) {
  return backgroundPresets[presetName] || null;
}

/**
 * Get all preset names
 * @returns {Array<string>} Array of preset names
 */
export function getPresetNames() {
  return Object.keys(backgroundPresets);
}

/**
 * Get preset metadata (without parameters)
 * @returns {Array<Object>} Array of preset metadata
 */
export function getPresetMetadata() {
  return Object.entries(backgroundPresets).map(([key, preset]) => ({
    key,
    name: preset.name,
    description: preset.description,
  }));
}



